//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpcomingMoviesMob.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AllResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AllResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpcomingMoviesMob.Resources.AllResources", typeof(AllResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.themoviedb.org/3/movie/upcoming?api_key=.
        /// </summary>
        internal static string AllMoviesLinkTemplate {
            get {
                return ResourceManager.GetString("AllMoviesLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ?api_key=.
        /// </summary>
        internal static string ApiKeyForLink {
            get {
                return ResourceManager.GetString("ApiKeyForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на buttons.
        /// </summary>
        internal static string ButtonsText {
            get {
                return ResourceManager.GetString("ButtonsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /credits?api_key=.
        /// </summary>
        internal static string CastAndCrewLinkTemplate {
            get {
                return ResourceManager.GetString("CastAndCrewLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  days ago.
        /// </summary>
        internal static string ForDaysLeft {
            get {
                return ResourceManager.GetString("ForDaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /images?api_key=.
        /// </summary>
        internal static string ForImageLinkTemplate {
            get {
                return ResourceManager.GetString("ForImageLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://www.themoviedb.org/t/p/w600_and_h900_bestv2.
        /// </summary>
        internal static string ForImageURL {
            get {
                return ResourceManager.GetString("ForImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://www.google.com.
        /// </summary>
        internal static string GoogleLink {
            get {
                return ResourceManager.GetString("GoogleLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No internet connection. Check the connection and restart the program.
        /// </summary>
        internal static string InternetConnectionError {
            get {
                return ResourceManager.GetString("InternetConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;language=en-US&amp;query=.
        /// </summary>
        internal static string LanguageAndQueryTemplateForLink {
            get {
                return ResourceManager.GetString("LanguageAndQueryTemplateForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.themoviedb.org/3/movie/.
        /// </summary>
        internal static string MovieLinkTemplate {
            get {
                return ResourceManager.GetString("MovieLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No videos available.
        /// </summary>
        internal static string NoAvailableVideosMessage {
            get {
                return ResourceManager.GetString("NoAvailableVideosMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        internal static string NoButtonText {
            get {
                return ResourceManager.GetString("NoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string NoDaysLeft {
            get {
                return ResourceManager.GetString("NoDaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png.
        /// </summary>
        internal static string NoImagePath {
            get {
                return ResourceManager.GetString("NoImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No more pages.
        /// </summary>
        internal static string NoMorePagesMessage {
            get {
                return ResourceManager.GetString("NoMorePagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;page=.
        /// </summary>
        internal static string PageForLink {
            get {
                return ResourceManager.GetString("PageForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;region = UA.
        /// </summary>
        internal static string RegionForLink {
            get {
                return ResourceManager.GetString("RegionForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.themoviedb.org/3/search/multi?api_key=.
        /// </summary>
        internal static string SearchLinkTemplate {
            get {
                return ResourceManager.GetString("SearchLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.themoviedb.org/3/tv/.
        /// </summary>
        internal static string SeriesLinkTemplate {
            get {
                return ResourceManager.GetString("SeriesLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;sort_by=popularity.
        /// </summary>
        internal static string SortForLink {
            get {
                return ResourceManager.GetString("SortForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.themoviedb.org/3/person/.
        /// </summary>
        internal static string TemplatePersonBio {
            get {
                return ResourceManager.GetString("TemplatePersonBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.themoviedb.org/3/tv/popular?api_key=.
        /// </summary>
        internal static string TemplatePopularLink {
            get {
                return ResourceManager.GetString("TemplatePopularLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.themoviedb.org/3/tv/.
        /// </summary>
        internal static string TemplateSeriesLink {
            get {
                return ResourceManager.GetString("TemplateSeriesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.themoviedb.org/3/trending/all/day?api_key=.
        /// </summary>
        internal static string TemplateTrendingToday {
            get {
                return ResourceManager.GetString("TemplateTrendingToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.themoviedb.org/3/trending/all/week?api_key=.
        /// </summary>
        internal static string TemplateTrendingWeek {
            get {
                return ResourceManager.GetString("TemplateTrendingWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /mqdefault.jpg.
        /// </summary>
        internal static string ThumbnailQuality {
            get {
                return ResourceManager.GetString("ThumbnailQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown button value.
        /// </summary>
        internal static string UnknownButtonText {
            get {
                return ResourceManager.GetString("UnknownButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /videos?api_key=.
        /// </summary>
        internal static string VideoLinkTemplate {
            get {
                return ResourceManager.GetString("VideoLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to close the app?.
        /// </summary>
        internal static string WantToClose {
            get {
                return ResourceManager.GetString("WantToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string YesButtonText {
            get {
                return ResourceManager.GetString("YesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://www.youtube.com/watch?v=.
        /// </summary>
        internal static string YouTubeLinkTemplate {
            get {
                return ResourceManager.GetString("YouTubeLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://img.youtube.com/vi/.
        /// </summary>
        internal static string YouTubeThumbnailTemplate {
            get {
                return ResourceManager.GetString("YouTubeThumbnailTemplate", resourceCulture);
            }
        }
    }
}
